sudo: required
services:
- docker
env:
  global:
    secure: Ai+rz1pNHqv0NlXvTNq1bbnEdZD7DZPit7VFd2xQnZpYiBusmuRS7q2vmIBQeWxvIRVkYRE+j59M6x9GeJ/ZvfDJ5t6GIdL44dvTmzsUDZEUkKU9VTg3wOeYK74l4svcGFGIrNXrXKMgNfVkPjylmYiC53FsQ4UCYv41KyB7l/YnYvtauq57GUlgkcjBYS/8PPVTH6ORZLDEnyMuxZLlnlzp2rAb5+HW0P5OFtzMdkEKyVcJFA9dMLZQE/BMtPvqwkXdYnc7vTwYOnEFAj7y6fekdF3mKcXgrbv8V+qgnL5vs3NnvDsnKZeKjX29x2MNDlig0xGeVmOlGrmLuhZTc+DD+n61Ud47DIH5fziKeKbfVvquYVxTGtUxdCPOnvKuw7vhqYnIcYg3eMlQe3B4U3p5wSMNQlWWdD4QboFt20B3gRW2besfUCzmWtLhbOWObQGRLyg10Wo4Vyh12QN/y1JtqRf3aKc52/FnKkvsLo8DCe8vtrARBmDLuwKP2+Kp7i/Rm5ts57Ps67udw6ceeuYXNiHdeuhGp4lTpNLpR4qnmwGPhhIbgAxMaDm+U1peRIow92UycxoDWUjSRv+urdOp7yZKPHwFrIwT/PxFZrBh4TFxh7mAJXVcJuIbqE6QjCgeUhSvR3VBgnu+iugnQect90TTSzkCzfSQm9UxP/M=
script:
- docker build stretch
- docker build stretch/slim
- docker build buster
- docker build buster/slim
- docker build alpine3.10
after_success: |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    curl -sS -H "Content-Type: application/json" --data '{"build": true}' -X POST \
      https://hub.docker.com/api/build/v1/source/23e76a6c-9b2f-4012-a2eb-32128b053afb/trigger/${TRIGGER_TOKEN}/call/
  fi
